prkumar/uplink

- tests/test_builder.py
- tests/test_integration.py
- uplink/builder.py
- uplink/client.py
I used the Builder internally for the Consumer interface, but that can be changed quite easily.
I modified the tests to use the Consumer interface and the slightly modified Builder to fit the
new implementation - all tests pass!
I think this implementation may be a bit hard coded because Builder still exists, and as seen in the tests, you have to pass it an empty instantiated class that acts as a stub. That's a little funky - I might imagine just combining Consumer and Builder as one, and changing the tests so that they dont even touch builder, they just test Consumer immediately.
> Implements #3 - Use a Consumer interface

- docs/source/advanced.rst
- docs/source/index.rst
- Add subsection to documentation homepage that notifies reader of Uplink's support for concurrent requests 
- Under advanced usage section in documentation, add separate subsections covering each concurrent client.
> Add examples of concurrent requests to documentation

- README.rst
- docs/source/index.rst
I've created a [Gitter community page](https://gitter.im/python-uplink/Lobby#) for this repository. The chat room provides a setting for users and contributors to ask questions, tease feature ideas, find love, etc., in a more informal space than GitHub PR and issue comments.
> Add Gitter Lobby badge to README and documentation landing page

- uplink/commands.py
Fixes the lack of support for HTTP Head ;)
- Add head support, which will basically do the same thing as @get, but not return the text attr of the response, only the headers attr.
> Add support for HTTP HEAD

- tests/test_utils.py
- uplink/builder.py
- uplink/commands.py
- uplink/utils.py
Fixes #23
- Change CallBuilder to not build upon init()
- RequestDefinitionBuilder builds on access
- Add memozie func
> Build requestdefinition on access, not constructor

- tests/test_builder.py
- uplink/builder.py
Fixes #26.
Simple change to allow the use case outlined in the issue, although now it will blindly try to instantiate any classes passed in, whether it implements the interface or not.
I couldn't figure out how to have pytest use a fixture within a fixture, along the lines of
```
@pytest.fixture(params=[None, http_client_mock, http_client_mock()])
```
so I went with the current workaround.
> Instantiate client adapter if a class is passed.

- tests/test_decorators.py
- tests/test_helpers.py
- uplink/helpers.py
Fixes #27.
- Method annotations should not annotate inherited consumer methods
> Fix method annotations so that they don't decorate inherited consumer methods

- .travis.yml
The Travis CI Python 2.7 build was failing to deploy the coverage report to coveralls.io. This commit replaces the `python-coveralls` library with `coveralls-python`. The latter library reruns the coverage report and quits when `coverage.py` fails to analyze `uplink/clients/aiohttp_.py` on Python 2.7, since the file includes a `yield from` statement that requires Python 3.3+. This commit makes a one line change to the Travis CI config file to use `coveralls-python`, which by default uses the coverage report created when running the tests with `tox`.
> Fix Python 2.7 coveralls.io build

- AUTHORS.rst
- uplink/types.py
Fixes #17
- Adds docstrings to the classes:
- uplink.types.Query
- uplink.types.QueryMap
- uplink.types.Header
- uplink.types.HeaderMap
- uplink.types.Field
- uplink.types.FieldMap
- uplink.types.Part
- uplink.types.PartMap
- uplink.types.Body
- uplink.types.Url
I believe I've messed up a bit on the "Attribute/Args/Params" description of the classes. Some of the classes I did a bit of guessing of what they will be used for. With that in mind this is a first PR to try and get some feedback on my work.
Please let me know what needs to be improved (apologies if it's a lot of things).
> Update uplink.types docstrings

- docs/source/conf.py
- examples/async-requests/asyncio_example.py
- tests/test_clients.py
- uplink/clients/__init__.py
- uplink/clients/aiohttp_.py
- uplink/clients/requests_.py
- uplink/clients/twisted_.py
- Update documentation for `TwistedClient` and `RequestsClient`
- Fix typo in `asyncio_example.py`
- Add `AiohttpClient.create` method, that lazily constructs an `aiohttp.ClientSession` given arguments that the class accepts on instantiation.
> Minor refactor of `clients` subpackage

- examples/async-requests/github.py
Fixes n/a .
I was trying to make the examples work and noticed that the file github.py didn't have a working example code, so I referred to the documentation and wrote these two bits of code to help people getting started.
I've commented them because when you run the asyncio_example.py the code in github.py will be run again.
Please let me know if you'd like me to change something 👍 
> Add code to execute example from github.py in async-requests folder

- tests/test_decorators.py
- uplink/decorators.py
With this changes a user can pass a string, list or dict to the decorator `@uplink.headers`. I've separated the str type from list type in the if statement but could try to work out another way to write this code.
**Tests:**
I've used the code in `examples/github.py` to test if everything still works without any issues. I was able to get the same results when passing a string, list or dict to the uplink.headers decorator.
The tests in `tests/tests_decorators.py` were also updated to include the different ways to write the headers decorator. To be honest there's some similar code on the test, let me know if you are okay with that or if you like me to change it.
That's all for now, I'll look forward to hear your feedback on this 👍 
> Allows the first argument of headers to be a str or list

- tests/test_decorators.py
- uplink/decorators.py
Fixes #41
This PR adds the `response_handler` decorator, that enables users to define custom response handling. 
To register a function as a custom response handler, decorate the function with this class. The decorated function should accept a single positional argument, an HTTP response object:
```python
@response_handler
def raise_for_status(response):
response.raise_for_status()
return response
```
Then, to apply custom response handling to a request method, simply decorate the method with the registered response handler:
```python
@raise_for_status
@get("/user/posts")
def get_posts(self):
"""Fetch all posts for the current users."""
```
To apply custom response handling on all request methods of a `uplink.Consumer` subclass, simply decorate the class with the registered response …
> Add decorator for defining custom response handlers

- tests/test_clients.py
- tests/test_decorators.py
- tests/test_hooks.py
- uplink/builder.py
- uplink/clients/aiohttp_.py
- uplink/clients/helpers.py
- uplink/clients/interfaces.py
- uplink/clients/requests_.py
- uplink/clients/twisted_.py
- uplink/decorators.py
- uplink/hooks.py
A decorator for creating custom error handlers.
To register a function as a custom error handler, decorate the function with this class. The decorated function should accept three positional arguments: (1) the type of the exception, (2) the exception instance raised, and (3) a traceback instance.
```python
@error_handler
def raise_api_error(exc_type, exc_val, exc_tb):
...
```
Then, to apply custom error handling to a request method, simply decorate the method with the registered error handler:
```python
@raise_api_error
@get("/user/posts")
def get_posts(self):
"""Fetch all posts for the current users."""
```
To apply custom error handling on all request methods of a `uplink.Consumer` subclass, simply decorate the class with the registered error handler:
```python
@raise_api_error
class …
```
> Add decorator for defining custom error handling

- tests/test_builder.py
- tests/test_clients.py
- tests/test_commands.py
- tests/test_converters.py
- tests/test_decorators.py
- tests/test_integration.py
- tests/test_types.py
- uplink/auth.py
- uplink/builder.py
- uplink/commands.py
- uplink/converters/__init__.py
- uplink/decorators.py
- uplink/hooks.py
- uplink/interfaces.py
- uplink/types.py
- uplink/utils.py
Fixes #64.
These commits enable users to use argument annotations with the constructor of a Consumer subclass. These annotations define all invocations of any request method defined on the subclass. For instance:
```python
class GitHub(uplink.Consumer):
def __init__(self, access_token: uplink.Query("access-token")):
...
```
> Set request properties from constructor arguments

- tests/conftest.py
- tests/test_builder.py
- tests/test_decorators.py
- tests/test_hooks.py
- tests/test_types.py
- tests/test_utils.py
- uplink/builder.py
- uplink/decorators.py
- uplink/helpers.py
- uplink/hooks.py
- uplink/interfaces.py
- uplink/types.py
- uplink/utils.py
Three changes proposed in this review. First, added the `equals` method for some argument annotations (e.g., `Query` and `Header`). This method takes a single argument, an acceptable value for the annotation, and creates a transaction hook that uses `ArgumentAnnotation.modify_request` to apply the annotation on a request. 
Second, added the `Consumer._inject` method. Can be used to add hooks in subclass constructors, for example.
```python
def __init__(self, base_url, access_token):
super(Consumer, self).__init__(base_url)
self._inject(Query("access_token").equals(access_token))
```
Third, added the `inject` decorator. Can be used to add hooks on all invocations of a request method:
```python
@inject(Query("sort").equals("pushed"))
@get("users/{user}/repos")
def …
```
> Add `Consumer._inject` method and `inject` decorator

- README.rst
- tests/test_decorators.py
- tests/test_types.py
- uplink/decorators.py
- uplink/types.py
These changes enable users to set nested JSON fields with `uplink.Field` and `uplink.json`. Tuples represent the path of nested field. For example, to achieve a payload like this:
```
{
"user":  {
"username": <<input value>>
}
}
```
We can construct an `uplink.Field` with the `name` parameter set to the tuple `("outer", "inner")`, such as in the following example:
```python
@uplink.json
@uplink.post("/user")
def create_user(self, username: uplink.Field(("user", "username"))):
pass
```
> Set Fields of a Nested JSON Object in Payload 

- tests/conftest.py
- tests/test_builder.py
- tests/test_converters.py
- tests/test_types.py
- uplink/builder.py
- uplink/clients/twisted_.py
- uplink/commands.py
- uplink/converters/__init__.py
- uplink/converters/interfaces.py
- uplink/converters/keys.py
- uplink/converters/marshmallow_.py
- uplink/converters/register.py
- uplink/converters/standard.py
- uplink/types.py
Here's are some key changes included in these commits:
* Added `register_converter_factory` decorator to register default converters. These converter factories are always used. 
* `MarshmallowConverter` is registered as a default converter if `marshmallow` is installed. This avoids the extra step of having users specify the converter when constructing a new consumer.
> Introduce decorator to register default converters

- tests/test_types.py
- uplink/commands.py
- uplink/types.py
Existing clients that may be using type hints in their function annotations might opt to use the `uplink.args` decorator instead of replacing their existing function annotations with fields like `uplink.Path` or `uplink.Query`. For instance:
```python
@uplink.args(uplink.Path("id"))
@uplink.get("/users/{id}")
def get_user(self, user_id: str):
pass
```
For such use cases, these changes will ensure that the argument (i.e., `user_id` in the above example) retains the type of it's corresponding argument (i.e., `str`). This can be useful, since -- for example -- uplink's converter layer will then try to convert any value passed into `user_id` argument into a `str`. This differs from the existing behavior, as the converter layer would not have handled the value conversion at all since …
> Make it easier to integrate Uplink into existing code that uses type hints

- docs/source/converters.rst
- tests/test_decorators.py
- uplink/commands.py
- uplink/converters/typing_.py
- uplink/decorators.py
Specifies that the decorated consumer method should return a JSON object.
Example
--------
```python
@returns.json
@get("/users/{username}")
def get_user(self, username):
"""Get a specific user."""
```
Returning a Specific JSON Field
=======================
This decorator accepts two optional arguments. The `member` argument accepts a string or tuple that specifies the path of an internal field in the JSON document.
For instance, consider an API that returns JSON responses that, at the root of the document, contains both the server-retrieved data and a list of relevant API errors:
```json
{
"data": { "user": "prkumar", "id": 10432 },
"errors": []
}
```
If returning the list of errors is unnecessary, we can use the `member` argument to strictly return the inner field `data`:
```python …
```
> Add `returns.json` decorator

- tests/test_commands.py
- uplink/commands.py
This change enables end-users to annotate method arguments without an extra decorator, `uplink.args`:
```python
@put("user", args={"info": Body})
def create_user(self, **info): pass
```
The parameter also accepts a sequence in lieu of a map:
```python
@put("user", args=(Body,))
def create_user(self, **info): pass
> Add "args" parameter for HTTP method decorators

- tests/test_models.py
- uplink/models.py
Contains decorators for convenient registration of serializers and deserializers
> Add `uplink.models` module

- CHANGELOG.rst
- tests/test_arguments.py
- tests/test_commands.py
- tests/test_returns.py
- uplink/__about__.py
- uplink/arguments.py
- uplink/commands.py
- uplink/returns.py
Relates to #89 
- Decorator ``uplink.returns.model`` for specifying custom return type without
indicating a specific data deserialization format.
- Have ``uplink.Body`` decorator accept any type, not just mappings.
- Reintroduce the ``uplink.returns`` decorator.
> Release Hotfix v0.5.1

- .travis.yml
- CHANGELOG.rst
- tests/test_integration.py
- uplink/__about__.py
- uplink/returns.py
This issue was initially reported on [gitter](https://gitter.im/python-uplink/Lobby?at=5b0eca34ba1a351a68d794e2) by @liiight.
Applying ``returns.json`` decorator without arguments should produce JSON
responses when the decorated method is lacking a return value annotation. 
Here's an example to reproduce the issue on v0.5.1:
```python
from uplink import Consumer, returns, get
@returns.json
@get("/users/{user}/repos")
def get_repos(self, user):
pass
github = GitHub("https://api.github.com")
github.get_repos("prkumar")
```
> Fix usage of returns.json without arguments

- AUTHORS.rst
- CHANGELOG.rst
- tests/test_hooks.py
- uplink/__about__.py
- uplink/hooks.py
Fixed
-----
- Issue where adding two or more response handlers (i.e., functions decorated
with ``uplink.response_handler``) to a method caused a ``TypeError`.
> Release Hotfix v0.5.3

- docs/source/auth.rst
- docs/source/consumer.rst
- docs/source/index.rst
- docs/source/quickstart.rst
- docs/source/types.rst
- tests/test_session.py
- uplink/arguments.py
- uplink/builder.py
- uplink/decorators.py
- uplink/interfaces.py
- uplink/session.py
The following feature was initially proposed by @liiight:
The `session` property of a `uplink.Consumer` instance exposes the instance's configuration and allows for the persistence of certain properties across requests sent from that instance.
Users can provide default headers and query parameters for requests sent from a consumer instance through its `session` property:
```python
class TodoApp(uplink.Consumer):
def __init__(self, username, password)
api_key = create_api_key(username, password)
self.session.params["api_key"] = api_key
def get_todos(self, sort_by: uplink.Query("sort_by")):
"""Retrieves all todo items."""
```
Similar to the annotation style, headers and query parameters added through the `session` are applied to all requests sent from the consumer instance.
Notably, in case …
> Add `session` property to `Consumer` base class

- docs/source/decorators.rst
- docs/source/quickstart.rst
- tests/test_decorators.py
- uplink/decorators.py
Similar to the `headers` decorator,  params adds static query parameters for API calls.
```python
@params({"sort": "created"})
@get("/user")
def get_user(self):
"""Get the current user"""
```
When used as a class decorator, :py:class:`params` applies to
all consumer methods bound to the class:
```python
@params({"client_id": "my-app-client-id"})
...
```
`params` takes the same arguments as `dict`.
> Add `params` decorator

- uplink/clients/aiohttp_.py
Fixes #99 
- Use `functools.partial` to register a partial for the `aiohttp.ClientSession.close` coroutine, running it in an event loop on exit instead.
P.S. I am fairly new to `asyncio`, so please excuse my ignorance if this is not the best method to do so.
> Support registering aiohttp.ClientSession.close coroutine at exit

- AUTHORS.rst
- CHANGELOG.rst
- uplink/__about__.py
- uplink/clients/aiohttp_.py
Fixed
-----
- When using ``uplink.AiohttpClient`` with ``aiohttp>=3.0``, the underlying
``aiohttp.ClientSession`` would remain open on program exit. #100
> Release Hotfix v0.5.4

- uplink/decorators.py
Small indentation change to fix the broken code block for the `json` decorator class on https://uplink.readthedocs.io/en/stable/decorators.html
> Update indentation on json decorator example

- examples/marshmallow/schemas.py
- uplink/converters/marshmallow_.py
After marshmallow 3.0, `Schema().load` and `Schema().dump` don't return a `(data, errors)` tuple any more. Only `data` is returned.
See: https://marshmallow.readthedocs.io/en/3.0/upgrading.html
This tiny PR accommodates these changes for our examples and integrations with `marshmallow`.
> Address changes to Schema().load and Schema().dump in marshmallow v3

- AUTHORS.rst
- examples/handler_callbacks/README.md
- examples/handler_callbacks/Server.py
- examples/handler_callbacks/handlers_example.py
Fixes #113  .
- Adds an example of how to use response_handler and error_handler when crafting a proxy. The response_handler prints google.com response status code. error_handler purposely loads an invalid URL and prints some text indicating an error was encountered
- Add name to AUTHORS.rst
> Issue #113: Adds an example of repsonse_handler and error_handler

- tests/unit/test_arguments.py
- uplink/arguments.py
Fixes #125.
- Adds an `encode_none` parameter to `Query` which lets users specify if at all, and if yes how a value of `None` should be sent to the service.
This changes behavior slightly: if a parameter is `None` (per its default value or because the user set it), previously it was encoded as `...?name=None`. To retain this behavior, a user would have to specify `Query(..., encode_none="None")`.
> Let users specify if/how None values are encoded

- docs/source/dev/types.rst
- tests/unit/test_arguments.py
- tests/unit/test_converters.py
- uplink/__init__.py
- uplink/arguments.py
- uplink/converters/keys.py
Fixes #131 .
- add ``Timeout`` argument annotation to be able to pass timeout as consumer method argument or to inject it as transaction hook
- add ``Identity`` converter key to pass given value as is to use it in ``Timeout`` described above
> Add timeout argument annotation

- docs/source/dev/decorators.rst
- docs/source/user/quickstart.rst
- tests/integration/test_retry.py
- tests/unit/test_clients.py
- tests/unit/test_retry.py
- uplink/clients/aiohttp_.py
- uplink/retry/__init__.py
- uplink/retry/_helpers.py
- uplink/retry/retry.py
- uplink/retry/stop.py
- uplink/retry/when.py
These changes add a `when` argument to the `@retry` decorator and also the `retry.when` module that exposes retry conditions. The `when` argument should be used to set a retry predicate/condition that details **when** a retry should be attempted. For example, the `retry.when.status` method is a predicate that prompts retries on a specific HTTP response status code. Also, these changes add support for joining retry predicates (e.g., `retry.when.*`) using the `|` operator. Further, the `|` operator can also be used with retry stopping strategies (e.g., `retry.stop.*`). Here's a simple example that illustrates some of these changes:
```python
from uplink import retry, Consumer, get
@retry(
when=retry.when.status(503) | retry.when.raises(Exception) …
```
> Enhance @retry decorator with `when` argument

- tests/integration/test_ratelimit.py
- tests/unit/test_helpers.py
- uplink/builder.py
- uplink/helpers.py
- uplink/ratelimit.py
Proposed Changes:
- The rate limit is enforced separately for each host-port combination. Effectively, requests are grouped by host and port, and the number of requests within a time period are counted and capped separately for each group. 
For example, consider the following consumer:
```python
class GitHub(uplink.Consumer):
@uplink.ratelimit(calls=1, period=10, raise_on_limit=True)
@uplink.get("repos/{user}/{repo}/issues/{issue}")
def get_issue(self, user, repo, issue):
pass
```
These changes prevent two separate instances of the above consumer from blocking each other if the they point to separate hosts:
```python
github1 = GitHub(base_url="https://api.github.com", client=mock_client)
github2 = GitHub(base_url="https://hosted-github-enterprise.com/api", client=mock_client) …
```
> Keep a separate rate limit for each host-port combination

- tests/unit/test_decorators.py
- tests/unit/test_helpers.py
- uplink/helpers.py
Fixes #119 .
- Apply class decorator to all consumer method including inherited
- Effectively revert changes made in #27
> Apply class decorators to all consumer methods

- AUTHORS.rst
- tests/unit/test_auth.py
- uplink/auth.py
This adds more auth classes designed to be used when initializing a
Consumer subclass. There are two generic AuthToken types that may
be used directly or may be subclassed by API library authors to define
the relevant query parameter or header.
There is also a MultiAuth type which allows for passing in a list of auth
methods, so that they all take effect.
The purpose of the generic AuthToken types is to make it simple for
uplink-based libraries to provide a standardized way to authenticate
with their api.
The purpose of MultiAuth is to allow for multiple auth methods. This may
be required when ProxyAuth needs to be combined with another auth
method, or when an API requires multiple auth tokens.
> Add and expose auth types: MultiAuth ApiToken*

- .travis.yml
- README.rst
- uplink/__about__.py
Fixes #148 
Fixed
-----
- Removed non-ASCII characters in README that broke installations on environments where `ascii` 
encoding is the default.
- Reverted back to deploying a wheel distribution on release
> Fix bad installations on environments that use ASCII encoding as default

- tests/unit/test_builder.py
- uplink/arguments.py
- uplink/builder.py
- uplink/commands.py
- uplink/decorators.py
- uplink/interfaces.py
I noticed that, when writing a superclass that is extended by two separate subclasses, class-level decorators are shared across the siblings. You can reproduce this issue with the following example:
```python
@get("users/{id}")
def get(self, id):
pass
@response_handler(lambda _: 2)
class GitHub2(GitHub):
pass
@response_handler(lambda x: x.json())
class GitHub3(GitHub):
pass
print(GitHub2("https://api.github.com").get_user("prkumar"))
print(GitHub3("https://api.github.com").get_user("prkumar"))
```
Running the above code snippet, you'll notice that the first invocation will throw an `AttributeError` since the response is wrapped by both `lambda _: 2` and `lambda x: x.json()`; notably, the latter handler receives and `int` (i.e., `2`) as it's input, which doesn't …
> Stop sharing class decorators across siblings

- tests/integration/test_returns.py
- tests/unit/test_commands.py
- tests/unit/test_returns.py
- uplink/commands.py
- uplink/decorators.py
- uplink/returns.py
Fixes #144 and #145.
- Allow a `@returns.*` decorator to override a consumer method's return annotation as the assigned schema used for deserialization (#144)
- Properly cascade `@returns.*` decorators when used as class decorators (#145)
> Refactor @returns.* decorator implementations (#144, #145)

- docs/source/dev/types.rst
- tests/integration/test_handlers.py
- tests/unit/conftest.py
- tests/unit/test_arguments.py
- tests/unit/test_builder.py
- tests/unit/test_helpers.py
- tests/unit/test_session.py
- uplink/__init__.py
- uplink/arguments.py
- uplink/builder.py
- uplink/clients/io/execution.py
- uplink/helpers.py
- uplink/session.py
Fixes #143.
The `Context` annotation can be used to pass data to middleware implemented as a `MethodAnnotation`, like the `cache` decorator that @kaidokert proposed on [gitter](https://gitter.im/python-uplink/Lobby?at=5c69f8e5dc3f0523ccd21e5a).
> Add `Context` argument annotation

- docs/source/user/quickstart.rst
- docs/source/user/tips.rst
- tests/integration/test_extend.py
- uplink/commands.py
- uplink/decorators.py
Fixes #151
**Consumer methods** are methods decorated with Uplink's HTTP method decorators,
such as `@get` or `@post` (see
[here](https://uplink.readthedocs.io/en/latest/user/quickstart.html#making-a-request) for more background).
Consumer methods can be used as decorators to minimize duplication across similar
consumer method definitions.
For example, you can define consumer method templates like so:
```python
from uplink import Consumer, get, json
@returns.json
@json
@get
def get_json():
"""Template for GET request that consumes and produces JSON."""
@get_json("/users/{user}")
def get_user(self, user):
"""Fetches a specific GitHub user."""
```
Further, you can use this technique to remove duplication across definitions
of similar consumer methods, whether or not …
> Extend Consumer Methods to Reduce Boilerplate

- setup.py
Twisted 19.7.0 [drops py3.4 support](https://github.com/twisted/twisted/blob/trunk/NEWS.rst#deprecations-and-removals).
> Pin twisted to <=v19.2.1 for py3.4

- CHANGELOG.rst
- tests/unit/test_arguments.py
- uplink/arguments.py
> Omit `Header` with `None` value from request

- tests/integration/test_basic.py
- tests/unit/test_arguments.py
- tests/unit/test_builder.py
- tests/unit/test_commands.py
- tests/unit/test_helpers.py
- uplink/arguments.py
- uplink/builder.py
- uplink/commands.py
- uplink/helpers.py
Fixes #164 .
- Check the type so `build()` isn't called on an already resolved string URL.
> Fix uplink.Url by checking url type (fixes #164)

- setup.py
Our CI build failures are related to pytest-dev/pytest#5903. We initially restricted pytest up to v4.1 in 64952e3 because pytest_twisted wasn't behaving well with the latest version of pytest at the time.
> Fix Travis CI build by upgrading pytest

- setup.py
Currently ``uplink`` wheel contains ``tests`` subpackages but shouldn't. It happens because ``exclude`` argument to ``find_packages()`` function makes ``setuptools`` to exclude packages enumerated in that argument but not their subpackages and thus ``tests.unit`` and ``tests.integration`` appear in the resulting wheel.
- Exclude ``tests.*`` subpackages together with ``tests``.
> Exclude tests subpackages from resulting Python wheel

- .travis.yml
- CHANGELOG.rst
- Pipfile
- README.rst
- docs/source/user/quickstart.rst
- setup.py
- tests/integration/test_basic.py
- tests/unit/test_arguments.py
- tests/unit/test_builder.py
- tests/unit/test_commands.py
- tests/unit/test_converters.py
- tests/unit/test_helpers.py
- tests/unit/test_utils.py
- tox.ini
- uplink/__about__.py
- uplink/arguments.py
- uplink/auth.py
- uplink/builder.py
- uplink/commands.py
- uplink/converters/marshmallow_.py
- uplink/helpers.py
- Omit ``Header`` argument from request when its value is ``None``.
(#167, #169)
- Fix ``AttributeError`` raised on usage of ``uplink.Url``.
(#164, #165 by @cognifloyd)
- Exclude ``tests`` subpackages from wheel.
(#188 by @daa)
> Release v0.9.1

- .travis.yml
- docs/source/conf.py
The travis build for python 3.6 runs flake8 against particular files. Notably, we had `docs/conf.py` in this set, which was moved to `docs/source/conf.py`.
> Fix FileNotFoundError in Python 3.6 builds

- tests/integration/test_basic.py
- tests/unit/test_commands.py
- uplink/builder.py
- uplink/commands.py
- uplink/interfaces.py
This involves copying function attributes (e.g., docstrings) using
`functools.update_wrapper`.
Original post on Gitter:
https://gitter.im/python-uplink/Lobby?at=5efcf94ce0e5673398e865e2
> Make consumer method look like the original func

- AUTHORS.rst
- Pipfile
- README.rst
- docs/source/dev/converters.rst
- docs/source/index.rst
- docs/source/user/install.rst
- docs/source/user/serialization.rst
- setup.py
- tests/unit/test_converters.py
- uplink/converters/__init__.py
- uplink/converters/pydantic_.py
Fixes #146  .
This PR introduces pydantic as one of the available models. I'd like to hear your opinion before proceeding with docs.
> Pydantic support

- tests/unit/test_converters.py
- uplink/arguments.py
- uplink/converters/standard.py
> Update fallback strategies for converters

- tests/unit/test_converters.py
- uplink/converters/pydantic_.py
> Add support for complex pydantic models

- tests/unit/test_converters.py
- uplink/converters/pydantic_.py
- support passing pydantic original model as request body
```python
from pydantic import BaseModel
from uplink import Consumer, Body
class CreateRepo(BaseModel):
name: str
delete_branch_on_merge: bool = False
@post("user/repos")
def create_repo(self, repo: Body(type=CreateRepo)):
"""Creates a new repository for the authenticated user."""
github = GitHub(base_url="https://api.github.com")
repo = CreateRepo(name="my_favorite_new_project")
github.create_repo(repo)  # instead of github.create_repo(repo.dict())
```
> support passing pydantic original model as request body

- CHANGELOG.rst
- docs/source/user/quickstart.rst
- tests/unit/test_converters.py
- uplink/__about__.py
- uplink/converters/pydantic_.py
Added
-----
- Support for serialization using a subclass of `pydantic`_'s `BaseModel` that
contains fields of a complex type, such as `datetime`.
- Support for passing a subclass of `pydantic`'s `BaseModel` as the request
body.
> Release v0.9.3

- uplink/arguments.py
- uplink/auth.py
- uplink/clients/io/interfaces.py
- uplink/commands.py
- uplink/converters/__init__.py
- uplink/converters/typing_.py
- uplink/decorators.py
- Fix the import path of the ABC classes used in the project.
> fix(collections): importing ABCs from collections directly is deprecated

- CHANGELOG.rst
- tests/unit/test_converters.py
- tests/unit/test_decorators.py
- tests/unit/test_hooks.py
- uplink/__about__.py
- uplink/arguments.py
- uplink/auth.py
- uplink/clients/io/interfaces.py
- uplink/clients/io/transitions.py
- uplink/commands.py
- uplink/converters/__init__.py
- uplink/converters/pydantic_.py
- uplink/converters/standard.py
- uplink/converters/typing_.py
- uplink/decorators.py
Fixed
-----
- A type set as a consumer method's return annotation should not be used to
deserialize a response object if no registered converters can handle the type.
([3653a672ee](https://github.com/prkumar/uplink/commit/3653a672ee0703119720d0077bb450649af5459c))
> Release v0.9.4

- examples/async-requests/asyncio_example.py
- Update asyncio example to use async/await syntax in Python 3.7 or later
> Update asyncio example to use async/await syntax in Python 3.7 or later

- tests/integration/__init__.py
- tests/integration/test_form_url_encoded.py
- tests/integration/test_multipart.py
- uplink/converters/keys.py
> Fix @uplink.*Map to not throw error if converter is None

- .travis.yml
- setup.py
Adding 3.9 and 3.10 to Travis CI config.
Context: #237
> Add 3.9 and 3.10 to travis build

- .github/ISSUE_TEMPLATE/question.md
- .gitignore
- .pre-commit-config.yaml
- .travis.yml
- AUTHORS.rst
- README.rst
- setup.py
- tests/integration/__init__.py
- tests/integration/test_form_url_encoded.py
- tests/integration/test_multipart.py
- tests/unit/test_auth.py
- tox.ini
- uplink/arguments.py
- uplink/auth.py
- uplink/clients/io/interfaces.py
- uplink/commands.py
- uplink/compat.py
- uplink/converters/__init__.py
- uplink/converters/keys.py
- uplink/converters/typing_.py
- uplink/decorators.py
Fixes #217 .
- Return support Python 2.7
> Fix uplink with Python 2.7

- uplink/arguments.py
the docstring in docs which is referenced https://uplink.readthedocs.io/en/stable/dev/types.html?highlight=path#uplink.Path, and is different than what's in the quickstart: https://uplink.readthedocs.io/en/stable/user/quickstart.html#path-parameters
- update docstring in arguments.py
> Update arguments.py - update docstring to match quickstart

- .gitignore
- docs/source/dev/decorators.rst
- tests/integration/test_retry.py
- tests/unit/test_retry.py
- uplink/retry/__init__.py
- uplink/retry/backoff.py
- uplink/retry/retry.py
Add a new base class, `uplink.retry.RetryBackoff`, which can be extended to implement custom backoff strategies. Subclasses can override three methods:
- `get_timeout_after_response(request, response)`: Returns the number of seconds to wait before retrying the request, or ``None`` to indicate that the given response should be returned.
- `get_timeout_after_exception(request, exc_type, exc_val, exc_tb)`: Returns the number of seconds to wait before retrying the request, or ``None`` to indicate that the given exception should be raised.
- `handle_after_final_retry()`: Handles any clean-up necessary following the final retry attempt.
An instance of a `RetryBackoff` subclass can be provided through the `backoff` argument of the `@retry` decorator.
#238
> Add `RetryBackoff` to support custom @retry backoff strategies

- CHANGELOG.rst
- tests/integration/test_returns.py
- tests/unit/test_returns.py
- uplink/returns.py
Fix ``@returns.json`` to cast JSON response (or field referenced by the ``key`` argument) using the ``type`` argument when the given type is callable. This restores behavior that was inadvertently changed in v0.9.3.
Example:
```python
@uplink.returns.from_json(key=("data", 0, "size"), type=int)
@uplink.get("/users/{user}/repos")
def get_first_repo_size(self, user):
pass
```
```python
assert github.get_first_repo_size("prkumar") == 300
```
#215
> Fix `@returns.json` support for casting response using provided type

- CHANGELOG.rst
- tests/conftest.py
- tests/integration/test_handlers_aiohttp.py
- tests/unit/test_hooks.py
- uplink/builder.py
- uplink/clients/aiohttp_.py
- uplink/compat.py
- uplink/hooks.py
Async callbacks are being wrapped by ThreadedCoroutine when they shouldn't be. For some context, the purpose of ThreadedCoroutine is to allow sync callbacks with aiohttp client. When the callback is an async function, [this condition](https://github.com/prkumar/uplink/blob/master/uplink/clients/aiohttp_.py#L89) should skip this behavior.
Fixes #256
> Do not wrap async function with threaded_callback

- CHANGELOG.rst
- tests/conftest.py
- tests/integration/test_basic.py
- tests/integration/test_handlers.py
- tests/integration/test_handlers_aiohttp.py
- tests/integration/test_returns.py
- tests/unit/test_hooks.py
- uplink/__about__.py
- uplink/builder.py
- uplink/clients/aiohttp_.py
- uplink/compat.py
- uplink/hooks.py
Fixed
-----
- Fix behavior of async ``@response_handler`` with ``AiohttpClient``. (#256)
> Release v0.9.7

- .travis.yml
Seems that travis is using cached wheel of newer version, which is causing the bug in 60.9 to remain although we've pinned to 60.8.2.
> Remove setuptools from cache before reinstalling

- .github/workflows/pre-commit.yml
The action was compromised:
https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
> Remove tj-actions/changed-files

- docs/source/user/tips.rst
- tests/unit/test_arguments.py
- uplink/arguments.py
- Allow argument annotations with generics syntax:
```python
class GitHub(uplink.Consumer):
@uplink.get("user")
def get_user(self, authorization: Header["Authorization"]):
"""Get an authenticated user."""
```
> Allow arguments initialization using subscription syntax

- CONTRIBUTING.md
- pyproject.toml
- uv.lock
- Define `marshmallow`/`pydantic`/`aiohttp`/`twisted` as optional dependencies so that they can be used as extras (e.g. `uplink[pydantic]`).
- Define `pytest` as `dev` dependency group.
Attention: @prkumar @leiserfg
> Use optional dependencies instead of dependency groups
